### ISSUE TITLE
Support Env Variables As Template Inputs

### ISSUE THREAD

**Issue by mcmah309** [mcmah309/containeryard#1]
Currently only user provided variables can be used as inputs to a module in yard.yaml

```yaml
...

outputs:
  Containerfile:
    - base:
        version: "24.04"
```
Environment variables should be acceptable as well
```yaml
...

outputs:
  Containerfile:
    - base:
        version: $VERSION
```
