### ISSUE TITLE
Add Pre-Build Hook And Post-Build Hook

### ISSUE THREAD

**Issue by mcmah309** [mcmah309/containeryard#13]
Run before and after the regular code executed through `yard build`.

e.g
```yaml
hooks:
    pre: yard update
    post: podman build . -t name

inputs:
...
outputs:
...
```
Note: should probably reload the `yard.yaml` file if something like `yard update` will be allowed.

- Add flag to run build without hooks

**Comment by mcmah309** [comment]
Done
```yaml
hooks:
    build:
        pre: yard update
        post: podman build . -t name
```
