### ISSUE TITLE
Support Shell Commands In Template Variables

### ISSUE THREAD

**Issue by mcmah309** [mcmah309/containeryard#14]
Example use case:
```yaml
outputs:
  Containerfile:
    - git_config:
        user_name: $(git config --get user.name)
        email: $(git config --get user.email)
```
