### ISSUE TITLE
Support Single File Modules

### ISSUE THREAD

**Issue by mcmah309** [mcmah309/containeryard#17]
A single file module syntax should be supported. To support correct syntax highlighting in IDE's we should use `md` files syntax, but any type of file the follows the format of using two "\```" blocks should work. e.g `module.md`
\```yaml
```yaml
description: "hello module"
args:
optional:
    - flutter_version
```
\```
\```Dockerfile
```Dockerfile
RUN echo hello
```
\```
"Containerfile" block should also work.

In `yard.yaml`
```yaml
inputs:
    modules:
        module: path/to/module.md
```
