### ISSUE TITLE
Add Header For Each Merged Module

### ISSUE THREAD

**Issue by mcmah309** [mcmah309/containeryard#19]
When all the modules are merged together into a Containerfile, each section should have a header. e.g.

```yaml
inputs:
  modules:
    rust: path/to
```

```Dockerfile
#########################
# rust
#########################
```
